Repository GoogleCloudPlatform/bank-of-anthos, pull requests merged in 2020-11, with the labels that each got.

#389 postgres:12-alpine
  src/accounts-db/Dockerfile
  src/ledger-db/Dockerfile
Labels: cla: yes

#390 release/v0.3.1
  kubernetes-manifests/accounts-db.yaml
  kubernetes-manifests/balance-reader.yaml
  kubernetes-manifests/contacts.yaml
  kubernetes-manifests/frontend.yaml
  kubernetes-manifests/ledger-db.yaml
  kubernetes-manifests/ledger-writer.yaml
  kubernetes-manifests/loadgenerator.yaml
  kubernetes-manifests/transaction-history.yaml
  kubernetes-manifests/userservice.yaml
Labels: cla: yes

#391 [Resubmit] Fixing bug where balance isn't returned for accounts with no payments.
  src/balancereader/src/main/java/anthos/samples/bankofanthos/balancereader/TransactionRepository.java
Labels: cla: yes

#396 Update ledgermonolith README to export env vars for make commands
  src/ledgermonolith/README.md
Labels: cla: yes, priority: p2, type: cleanup

#392 Fix Monolith GCE image to use public debian image
  src/ledgermonolith/scripts/deploy-monolith.sh
Labels: cla: yes, priority: p2, what/bug

#398 Update ledgermonolith to properly allow bank connections via firewall
  Makefile
  README.md
  src/ledgermonolith/scripts/deploy-monolith.sh
Labels: cla: yes, priority: p1, type: bug

#404 ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  .github/workflows/ci-master.yaml
  .github/workflows/ci-pr.yaml
Labels: cla: yes

#402 Update ledgermonolith README with commands to run the full BoA app
  Makefile
  src/ledgermonolith/README.md
  src/ledgermonolith/scripts/build-artifacts.sh
  src/ledgermonolith/scripts/deploy-monolith.sh
Labels: cla: yes, priority: p3, type: docs

#408 Minor fixes in ledgermonolith-service
  Makefile
  src/ledgermonolith/README.md
  src/ledgermonolith/init/startup-script.sh
  src/ledgermonolith/scripts/build-artifacts.sh
  src/ledgermonolith/scripts/deploy-monolith.sh
Labels: cla: yes

#383 Add CloudSQL option for accounts-db, ledger-db
  README.md
  extras/cloudsql/README.md
  extras/cloudsql/arch.png
  extras/cloudsql/create_cloudsql_instance.sh
  extras/cloudsql/kubernetes-manifests/balance-reader.yaml
  extras/cloudsql/kubernetes-manifests/config.yaml
  extras/cloudsql/kubernetes-manifests/contacts.yaml
  extras/cloudsql/kubernetes-manifests/frontend.yaml
  extras/cloudsql/kubernetes-manifests/jwt-secret.yaml
  extras/cloudsql/kubernetes-manifests/ledger-writer.yaml
  extras/cloudsql/kubernetes-manifests/loadgenerator.yaml
  extras/cloudsql/kubernetes-manifests/populate-accounts-db.yaml
  extras/cloudsql/kubernetes-manifests/populate-ledger-db.yaml
  extras/cloudsql/kubernetes-manifests/transaction-history.yaml
  extras/cloudsql/kubernetes-manifests/userservice.yaml
  extras/cloudsql/setup_workload_identity.sh
Labels: cla: yes
